import math
import numpy as np

import rclpy
from rclpy.node import Node

from nav_msgs.msg import Odometry
from sensor_msgs.msg import JointState
from std_msgs.msg import Float64MultiArray


def deg2rad(deg):
    return deg * math.pi / 180.0


def smoothstep(s):
    return 3.0 * s**2 - 2.0 * s**3


def smoothstep_dot(s):
    return 6.0 * s - 6.0 * s**2


def wrap_angle(angle):
    return math.atan2(math.sin(angle), math.cos(angle))


def quaternion_to_euler(x, y, z, w):
    sinr_cosp = 2.0 * (w * x + y * z)
    cosr_cosp = 1.0 - 2.0 * (x * x + y * y)
    roll = math.atan2(sinr_cosp, cosr_cosp)

    sinp = 2.0 * (w * y - z * x)
    if abs(sinp) >= 1.0:
        pitch = math.copysign(math.pi / 2.0, sinp)
    else:
        pitch = math.asin(sinp)

    siny_cosp = 2.0 * (w * z + x * y)
    cosy_cosp = 1.0 - 2.0 * (y * y + z * z)
    yaw = math.atan2(siny_cosp, cosy_cosp)

    return roll, pitch, yaw


class FullAdaptiveController(Node):
    def __init__(self):
        super().__init__("full_adaptive_controller")

        # ==========================================================
        # Drone physical parameters
        # ==========================================================

        self.mass = 3.06
        self.g = 9.81

        self.l = 0.25
        self.k_yaw = 0.02

        self.f_min = 0.0
        self.f_max = 15.0

        # Desired position is initialized from the first odometry message.
        # This means: hold the initial spawn position.
        self.x_des = None
        self.y_des = None
        self.z_des = None
        self.yaw_des = None

        # ==========================================================
        # Adaptive position controller
        # chi_pos = [x, y, z]
        #
        # e = chi - chi_des
        # s = e_dot + Phi e
        # u = - Lambda s - rho * s_direction
        #
        # u_pos = [ax_cmd, ay_cmd, az_cmd]
        # ==========================================================

        self.Phi_pos = np.diag([
            1.40,   # x
            1.40,   # y
            1.40    # z
        ])

        self.Lambda_pos = np.diag([
            6.00,   # ax command
            6.00,   # ay command
            9.00    # az command
        ])

        self.K_hat_pos = np.array([0.01, 0.01, 0.01], dtype=float)
        self.nu_pos = np.array([10.0, 14.0, 14.0], dtype=float)

        self.adaptive_scale_pos = 0.015

        # Limits on commanded accelerations.
        self.ax_limit = 4.0
        self.ay_limit = 4.0
        self.az_limit = 10.0

        # Max desired tilt generated by the position controller.
        self.max_tilt_des = deg2rad(15.0)

        # ==========================================================
        # Adaptive attitude controller
        # chi_att = [roll, pitch, yaw]
        #
        # u_att = [Mx, My, Mz]
        # ==========================================================

        self.Phi_att = np.diag([
            3.5,   # roll
            3.5,   # pitch
            1.5    # yaw
        ])

        self.Lambda_att = np.diag([
            2.2,   # Mx
            2.2,   # My
            0.7    # Mz
        ])

        self.K_hat_att = np.array([0.01, 0.01, 0.01], dtype=float)
        self.nu_att = np.array([10.0, 14.0, 14.0], dtype=float)

        self.adaptive_scale_att = 0.015

        self.Mx_limit = 2.2
        self.My_limit = 2.2
        self.Mz_limit = 0.8

        self.delta = 0.1

        # ==========================================================
        # Arm controller gains
        # For now: stable PD task, relative to initial joint state.
        # ==========================================================

        self.joint_names = ["joint1", "joint2"]

        self.Kp_arm = np.diag([3.0, 1.2])
        self.Kd_arm = np.diag([0.4, 0.25])
        self.tau_arm_limit = 3.0

        self.q = np.zeros(2)
        self.q_dot = np.zeros(2)
        self.q0 = None

        # ==========================================================
        # Drone state
        # ==========================================================

        self.have_odom = False
        self.have_joint_state = False

        self.x = 0.0
        self.y = 0.0
        self.z = 0.0

        self.x_dot = 0.0
        self.y_dot = 0.0
        self.z_dot = 0.0

        self.roll = 0.0
        self.pitch = 0.0
        self.yaw = 0.0

        self.roll_rate = 0.0
        self.pitch_rate = 0.0
        self.yaw_rate = 0.0

        self.start_time = None
        self.last_time = None
        self.last_log_time = None

        # ==========================================================
        # ROS interfaces
        # ==========================================================

        self.create_subscription(
            Odometry,
            "/drone/odom",
            self.odom_callback,
            10
        )

        self.create_subscription(
            JointState,
            "/joint_states",
            self.joint_state_callback,
            10
        )

        self.motor_pub = self.create_publisher(
            Float64MultiArray,
            "/motor_thrust_commands",
            10
        )

        self.arm_pub = self.create_publisher(
            Float64MultiArray,
            "/arm_effort_controller/commands",
            10
        )

        self.timer = self.create_timer(0.01, self.control_loop)

        self.get_logger().info("Full adaptive controller started")
        self.get_logger().info("Waiting for /drone/odom and /joint_states...")

    # ==========================================================
    # Callbacks
    # ==========================================================

    def odom_callback(self, msg):
        self.x = msg.pose.pose.position.x
        self.y = msg.pose.pose.position.y
        self.z = msg.pose.pose.position.z

        self.x_dot = msg.twist.twist.linear.x
        self.y_dot = msg.twist.twist.linear.y
        self.z_dot = msg.twist.twist.linear.z

        q = msg.pose.pose.orientation
        self.roll, self.pitch, self.yaw = quaternion_to_euler(
            q.x, q.y, q.z, q.w
        )

        self.roll_rate = msg.twist.twist.angular.x
        self.pitch_rate = msg.twist.twist.angular.y
        self.yaw_rate = msg.twist.twist.angular.z

        if self.x_des is None:
            self.x_des = self.x
            self.y_des = self.y
            self.z_des = self.z
            self.get_logger().info(
                f"Initial position hold: "
                f"x_des={self.x_des:.3f}, "
                f"y_des={self.y_des:.3f}, "
                f"z_des={self.z_des:.3f}"
            )

        if self.yaw_des is None:
            self.yaw_des = self.yaw
            self.get_logger().info(f"Initial yaw_des = {self.yaw_des:.3f} rad")

        self.have_odom = True

    def joint_state_callback(self, msg):
        name_to_index = {name: i for i, name in enumerate(msg.name)}

        for i, joint_name in enumerate(self.joint_names):
            if joint_name not in name_to_index:
                return

            idx = name_to_index[joint_name]

            if len(msg.position) > idx:
                self.q[i] = msg.position[idx]

            if len(msg.velocity) > idx:
                self.q_dot[i] = msg.velocity[idx]

        if self.q0 is None:
            self.q0 = self.q.copy()
            self.get_logger().info(f"Initial arm q0 = {np.round(self.q0, 3)}")

        self.have_joint_state = True

    # ==========================================================
    # Trajectory for arm
    # ==========================================================

    def interpolate(self, q_start, q_goal, t, t_start, duration):
        if t <= t_start:
            return q_start, np.zeros(2)

        if t >= t_start + duration:
            return q_goal, np.zeros(2)

        s = (t - t_start) / duration
        sigma = smoothstep(s)
        sigma_dot = smoothstep_dot(s) / duration

        q_des = q_start + sigma * (q_goal - q_start)
        q_dot_des = sigma_dot * (q_goal - q_start)

        return q_des, q_dot_des

    def desired_arm_trajectory(self, t):
        q_home = self.q0.copy()

        q_pre_grasp = q_home + np.array([
            deg2rad(25.0),
            deg2rad(10.0)
        ])

        q_grasp = q_home + np.array([
            deg2rad(25.0),
            deg2rad(-5.0)
        ])

        q_retract = q_home + np.array([
            deg2rad(5.0),
            deg2rad(15.0)
        ])

        if t < 5.0:
            return q_home, np.zeros(2), "ARM_INITIAL_HOLD"

        elif t < 17.0:
            q_des, q_dot_des = self.interpolate(
                q_home,
                q_pre_grasp,
                t,
                t_start=5.0,
                duration=12.0
            )
            return q_des, q_dot_des, "ARM_MOVE_TO_PRE_GRASP"

        elif t < 25.0:
            q_des, q_dot_des = self.interpolate(
                q_pre_grasp,
                q_grasp,
                t,
                t_start=17.0,
                duration=8.0
            )
            return q_des, q_dot_des, "ARM_MOVE_TO_GRASP"

        elif t < 29.0:
            return q_grasp, np.zeros(2), "ARM_GRASP_HOLD"

        elif t < 37.0:
            q_des, q_dot_des = self.interpolate(
                q_grasp,
                q_retract,
                t,
                t_start=29.0,
                duration=8.0
            )
            return q_des, q_dot_des, "ARM_RETRACT"

        elif t < 45.0:
            q_des, q_dot_des = self.interpolate(
                q_retract,
                q_home,
                t,
                t_start=37.0,
                duration=8.0
            )
            return q_des, q_dot_des, "ARM_RETURN_HOME"

        else:
            return q_home, np.zeros(2), "ARM_HOME_HOLD_FINAL"

    # ==========================================================
    # Adaptive control law
    # ==========================================================

    def compute_adaptive_control(
        self,
        chi,
        chi_dot,
        chi_des,
        chi_dot_des,
        Phi,
        Lambda,
        K_hat,
        nu,
        adaptive_scale,
        dt,
        wrap_yaw_index=None
    ):
        e = chi - chi_des

        if wrap_yaw_index is not None:
            e[wrap_yaw_index] = wrap_angle(e[wrap_yaw_index])

        e_dot = chi_dot - chi_dot_des

        s = e_dot + Phi @ e

        xi = np.concatenate((e, e_dot))
        xi_norm = np.linalg.norm(xi)
        s_norm = np.linalg.norm(s)

        K_dot = np.array([
            s_norm - nu[0] * K_hat[0],
            s_norm * xi_norm - nu[1] * K_hat[1],
            s_norm * xi_norm**2 - nu[2] * K_hat[2],
        ])

        K_hat += K_dot * dt
        K_hat[:] = np.maximum(K_hat, 0.0)

        # Safety cap: evita che l'adattativo esploda quando c'è un grande errore transitorio.
        K_hat[:] = np.clip(K_hat, 0.0, 2.5)

        rho = (
            K_hat[0]
            + K_hat[1] * xi_norm
            + K_hat[2] * xi_norm**2
        )

        rho = float(np.clip(rho, 0.0, 3.0))

        s_direction = s / math.sqrt(s_norm**2 + self.delta)

        u = -Lambda @ s - adaptive_scale * rho * s_direction

        return u, e, s, rho

    # ==========================================================
    # Mixer
    # ==========================================================

    def mixer(self, F, Mx, My, Mz):
        B = np.array([
            [1.0,        1.0,        1.0,        1.0],
            [self.l,     self.l,    -self.l,    -self.l],
            [-self.l,    self.l,     self.l,    -self.l],
            [self.k_yaw, -self.k_yaw, self.k_yaw, -self.k_yaw],
        ])

        u = np.array([F, Mx, My, Mz])

        try:
            f = np.linalg.solve(B, u)
        except np.linalg.LinAlgError:
            self.get_logger().error("Mixer matrix is singular")
            f = np.zeros(4)

        return np.clip(f, self.f_min, self.f_max)

    # ==========================================================
    # Main loop
    # ==========================================================

    def control_loop(self):
        if not self.have_odom:
            return

        if (
            self.x_des is None
            or self.y_des is None
            or self.z_des is None
            or self.yaw_des is None
        ):
            return

        now = self.get_clock().now()

        if self.start_time is None:
            self.start_time = now
            self.last_time = now
            self.last_log_time = now
            self.get_logger().info("Controller time initialized")
            return

        dt = (now - self.last_time).nanoseconds * 1e-9
        self.last_time = now

        if dt <= 0.0 or dt > 0.1:
            self.get_logger().warn(f"Invalid dt={dt:.4f}, skipping")
            return

        t = (now - self.start_time).nanoseconds * 1e-9

        # ======================================================
        # Position adaptive control
        # ======================================================

        chi_pos = np.array([
            self.x,
            self.y,
            self.z
        ])

        chi_dot_pos = np.array([
            self.x_dot,
            self.y_dot,
            self.z_dot
        ])

        chi_des_pos = np.array([
            self.x_des,
            self.y_des,
            self.z_des
        ])

        chi_dot_des_pos = np.zeros(3)

        u_pos, e_pos, s_pos, rho_pos = self.compute_adaptive_control(
            chi=chi_pos,
            chi_dot=chi_dot_pos,
            chi_des=chi_des_pos,
            chi_dot_des=chi_dot_des_pos,
            Phi=self.Phi_pos,
            Lambda=self.Lambda_pos,
            K_hat=self.K_hat_pos,
            nu=self.nu_pos,
            adaptive_scale=self.adaptive_scale_pos,
            dt=dt,
            wrap_yaw_index=None
        )

        ax_cmd = np.clip(u_pos[0], -self.ax_limit, self.ax_limit)
        ay_cmd = np.clip(u_pos[1], -self.ay_limit, self.ay_limit)
        az_cmd = np.clip(u_pos[2], -self.az_limit, self.az_limit)

        # Small-angle mapping:
        # ax ≈ g * pitch
        # ay ≈ -g * roll
        pitch_des = ax_cmd / self.g
        roll_des = -ay_cmd / self.g

        roll_des = np.clip(roll_des, -self.max_tilt_des, self.max_tilt_des)
        pitch_des = np.clip(pitch_des, -self.max_tilt_des, self.max_tilt_des)

        # ======================================================
        # Attitude adaptive control
        # ======================================================

        chi_att = np.array([
            self.roll,
            self.pitch,
            self.yaw
        ])

        chi_dot_att = np.array([
            self.roll_rate,
            self.pitch_rate,
            self.yaw_rate
        ])

        chi_des_att = np.array([
            roll_des,
            pitch_des,
            self.yaw_des
        ])

        chi_dot_des_att = np.zeros(3)

        u_att, e_att, s_att, rho_att = self.compute_adaptive_control(
            chi=chi_att,
            chi_dot=chi_dot_att,
            chi_des=chi_des_att,
            chi_dot_des=chi_dot_des_att,
            Phi=self.Phi_att,
            Lambda=self.Lambda_att,
            K_hat=self.K_hat_att,
            nu=self.nu_att,
            adaptive_scale=self.adaptive_scale_att,
            dt=dt,
            wrap_yaw_index=2
        )

        Mx = np.clip(u_att[0], -self.Mx_limit, self.Mx_limit)
        My = np.clip(u_att[1], -self.My_limit, self.My_limit)
        Mz = np.clip(u_att[2], -self.Mz_limit, self.Mz_limit)

        # Total thrust.
        # If az_cmd > 0, increase thrust.
        # If az_cmd < 0, decrease thrust.
        tilt_comp = math.cos(self.roll) * math.cos(self.pitch)
        tilt_comp = max(tilt_comp, 0.5)

        F = self.mass * (self.g + az_cmd) / tilt_comp
        F = max(0.0, F)

        motor_thrusts = self.mixer(F, Mx, My, Mz)

        motor_msg = Float64MultiArray()
        motor_msg.data = motor_thrusts.tolist()
        self.motor_pub.publish(motor_msg)

        # ======================================================
        # Arm PD tracking
        # ======================================================

        if self.have_joint_state and self.q0 is not None:
            q_des, q_dot_des, arm_phase = self.desired_arm_trajectory(t)

            e_arm = q_des - self.q
            e_dot_arm = q_dot_des - self.q_dot

            tau_arm = self.Kp_arm @ e_arm + self.Kd_arm @ e_dot_arm
            tau_arm = np.clip(tau_arm, -self.tau_arm_limit, self.tau_arm_limit)

            arm_msg = Float64MultiArray()
            arm_msg.data = tau_arm.tolist()
            self.arm_pub.publish(arm_msg)

        else:
            q_des = np.zeros(2)
            tau_arm = np.zeros(2)
            arm_phase = "ARM_WAITING_FOR_JOINT_STATES"

        # ======================================================
        # Logging
        # ======================================================

        dt_log = (now - self.last_log_time).nanoseconds * 1e-9

        if dt_log > 1.0:
            self.last_log_time = now

            self.get_logger().info(
                f"t={t:.1f} | "
                f"pos=[{self.x:.2f}, {self.y:.2f}, {self.z:.3f}] "
                f"pos_des=[{self.x_des:.2f}, {self.y_des:.2f}, {self.z_des:.3f}] "
                f"vel=[{self.x_dot:.2f}, {self.y_dot:.2f}, {self.z_dot:.2f}] | "
                f"rpy=[{self.roll:.3f}, {self.pitch:.3f}, {self.yaw:.3f}] "
                f"rpy_des=[{roll_des:.3f}, {pitch_des:.3f}, {self.yaw_des:.3f}] | "
                f"pos_e={np.round(e_pos, 3)} "
                f"att_e={np.round(e_att, 3)} | "
                f"rho_pos={rho_pos:.3f} K_pos={np.round(self.K_hat_pos, 3)} | "
                f"rho_att={rho_att:.3f} K_att={np.round(self.K_hat_att, 3)} | "
                f"acc_cmd=[{ax_cmd:.2f}, {ay_cmd:.2f}, {az_cmd:.2f}] | "
                f"F={F:.2f} M=[{Mx:.2f}, {My:.2f}, {Mz:.2f}] | "
                f"motors={np.round(motor_thrusts, 2)} | "
                f"{arm_phase} q={np.round(self.q, 3)} "
                f"q_des={np.round(q_des, 3)} "
                f"tau={np.round(tau_arm, 3)}"
            )

    def stop_all(self):
        motor_msg = Float64MultiArray()
        motor_msg.data = [0.0, 0.0, 0.0, 0.0]
        self.motor_pub.publish(motor_msg)

        arm_msg = Float64MultiArray()
        arm_msg.data = [0.0, 0.0]
        self.arm_pub.publish(arm_msg)


def main(args=None):
    rclpy.init(args=args)

    node = FullAdaptiveController()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        try:
            if rclpy.ok():
                node.stop_all()
        except Exception as e:
            node.get_logger().warn(f"Could not send zero commands on shutdown: {e}")

        node.destroy_node()

        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()